### ISSUE TITLE
Can we set outputs ?

### ISSUE THREAD

**Issue by abouroubi** [JasonEtco/actions-toolkit#119]
Github Actions can have outputs, can we do that with this toolkit ?

If not, is there any restirction on importing the @actions/core in the same file that uses actions-toolkit ?

**Comment by JasonEtco** [comment]
:wave: You can definitely use `@actions/core` - in fact, it's used within `actions-toolkit`. I'd be open to adding a `tools.outputs` Proxy that works like `tools.inputs` though. I'm going to close this because there are no action items, but feel free to reopen if I've missed something.

**Comment by abouroubi** [comment]
A proxy for the outputs would be great, I'll see if I can make a PR for that
