### ISSUE TITLE
Integrate Signale logs with GH actions syntax

### ISSUE THREAD

**Issue by EndBug** [JasonEtco/actions-toolkit#136]
As of now, you can use the built-in logger to show errors, warnings, debug messages, and so on, but they don't use the GH actions syntax, and so they don't appear in the report.

I'd like to integrate the already existing methods with the proper syntax (you can add it as a prefix in Signale) and to add a couple of methods (such as groups)

It's still possible to create your own Signale instance or to just log them manually, but I think that since you're already providing a custom logger it would be nice to provide this kind of feature too.

I work on this myself and then open a PR if you think this would be a nice addition to the package.
Let me know!

**Comment by JasonEtco** [comment]
Hey @EndBug, thanks for the suggestion! I don't fully understand - are you referring to the special command syntax that Actions uses? Would logging an error be equivalent to calling [`core.error()`](https://github.com/actions/toolkit/tree/main/packages/core#logging)? If so - yeah, that makes sense, definitely something this library should just do magically. A PR would be great!

**Comment by EndBug** [comment]
Yeah, that's exactly what I intended
Great, I'll open a PR as soon I'm ready 👍🏻

**Comment by EndBug** [comment]
Hey @JasonEtco, I need an advice: I've developed this functionality, but the fact that GitHub already puts 'Error' and 'Warning' prefixes itself, doesn't it get redundant?

These are the current result from the `@actions/core` and `signale`:
<img src="https://user-images.githubusercontent.com/26386270/112286109-43c10c80-8c8b-11eb-808e-9eafc1db2aab.png" alt="@actions/core result" width="250">
<img src="https://user-images.githubusercontent.com/26386270/112286176-55a2af80-8c8b-11eb-934c-208ab23880c8.png" alt="signale result" width="600">

This is the current result with my version of `actions-toolkit`:
<img src="https://user-images.githubusercontent.com/26386270/112286221-63f0cb80-8c8b-11eb-9782-4e718e594513.png" alt="actions-toolkit result" width="500">

I'm afraid that the signale prefixes are kind of redundant, and maybe it would be better to omit them when it's logging a GitHub command. (I also have an option to avoid logging to GitHub on a single log, and in that case they would be normal)

What do you think?

**Comment by EndBug** [comment]
I'm just gonna go ahead and remove the redundant Signale prefix...

**Comment by JasonEtco** [comment]
@endbug awesome, I'll take a look there. Let's continue that conversation over in #137 - but I agree, the Actions UI has changed and now the Signale prefixes are redundant. It might even be worth removing Signale entirely in favor of a light abstraction that just uses `core#warn/debug/error`
