### ISSUE TITLE
Support use with GitHub Enterprise servers 

### ISSUE THREAD

**Issue by cpitchford** [JasonEtco/actions-toolkit#159]
The `.github` property of the Toolkit class instances lets me interact with GitHub cloud but it does not allow me to interact with a GitHub Enterprise Server. This causes issues when attempting to use this package in a GitHub action running from GitHub Enterprise

Without passing a 'baseUrl' property into the constructor of Octokit, it will default to using GitHub Cloud's API endpoint, rather than the API endpoint on the GitHub Enterprise Server.

The baseUrl parameter should be added here: https://github.com/JasonEtco/actions-toolkit/blob/c6c7208c521db3b7418dbc9cf5eab282a501250e/src/index.ts#L142

**Describe the solution you'd like**

Allow an additional parameter to be passed into the ToolKit constructor that might allow me to pass in the correct API endpoint URL or detect the URL from the environment variables GitHub Enterprise provides:

```
  process.env.GITHUB_API_URL == 'https://{hostname of GitHub Enterprise Server}/api/v3'
```

**Describe alternatives you've considered**

I have not found a work around. I replaced the `.github` property with my own correctly configured OctoKit class instance

**Comment by ConnorDY** [comment]
I have the same problem.
This also relates to this issue with your `create-an-issue` action:
https://github.com/JasonEtco/create-an-issue/issues/160

**Comment by EdouardF** [comment]
Hello @JasonEtco I'd like to use your action in my org but this PR is needed. Can you please go through it?
