### ISSUE TITLE
/command support

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/actions-toolkit#17]
It'd be great to provide a `/command` abstraction - something like:

```js
// In an issue/PR comment, `/pizza dominos pepperoni`
toolkit.command('pizza', async args => {
  // args -> ['dominos', 'pepperoni']
})
```

Or maybe...

```js
// on instead of command
toolkit.on('pizza', async args => console.log(args))
```

---

Memorializing a conversation in [this tweet](https://twitter.com/JasonEtco/status/1084294026965192704):

<img width="400" alt="image" src="https://user-images.githubusercontent.com/10660468/51088429-8858d100-172d-11e9-8be6-565f762bb7f5.png">

---

I think that @mscoutermarsh should work on this 😎😈

**Comment by JasonEtco** [comment]
Hi @mscoutermarsh cc [this tweet](https://twitter.com/mscccc/status/1089711776613117952)

**Comment by JasonEtco** [comment]
Random thought - this'd be a weird API, because we'd need to ensure that its only triggered by `issue_comment` events, and that thats clear in the docs. Internally, that might be:

```ts
class Toolkit {
  public command (name, handler) {
    if (this.context.event !== 'issue_comment') return
    // ...
  }
}
```

**Comment by macklinu** [comment]
> ```js
> // In an issue/PR comment, `/pizza dominos pepperoni`
> toolkit.command('pizza', async args => {
>   // args -> ['dominos', 'pepperoni']
> })
> ```

+1 to this API. I feel like registering a command like this would be more explicit than a generic event emitter/subscription API (e.g. `toolkit.on('pizza')`).

To clarify https://github.com/JasonEtco/actions-toolkit/issues/17#issuecomment-458245263, are you stating that the only event a command can respond to is the `issue_comment` event and that the docs should explicitly state that? I think that makes sense as a potential user of this feature - can't think of another use case right now where a slash command handler would respond to a different GitHub event type.

**Comment by JasonEtco** [comment]
@macklinu thanks for sharing your thoughts!

> To clarify [#17 (comment)](https://github.com/JasonEtco/actions-toolkit/issues/17#issuecomment-458245263), are you stating that the only event a command can respond to is the `issue_comment` event and that the docs should explicitly state that?

Yeah, it'd be to avoid a "gotcha" where folks use the API in an action that cannot, by definition, trigger the command. I'd want to avoid people accidentally thinking that a `push` might trigger a `/command` 😁 

It might be worth building up a list of what those events are - `issues`, `issue_comment`, `pull_request`, `commit_comment`, `pull_request_review_comment`, `pull_request_review` I think? Basically anything that can have a "body" 🤔

**Comment by tcbyrd** [comment]
@JasonEtco We should also ensure it doesn't respond to bots, to prevent infinite loop situations (helpful when a Bot responds with a list of commands you can use)

We do this in the [jira middleware](https://github.com/integrations/jira/blob/a82a07d1f619740a6d2dcf74ab4a831009bb0c4f/lib/github/middleware.js#L6-L9):

```js
if (context.payload.sender.type === 'Bot') {
  return
}
