### ISSUE TITLE
A "store" for sharing information across actions

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/actions-toolkit#28]
Sharing data between actions _can_ be done, but its a little tricky. A workflow has a shared file-system (in `/github/workspace`), so data can be written and read from a file across actions.

However, this is can be kinda tricky to get right. I'd love to build a "store" of sorts, that just reads/writes from a namespaced file. Something like:

```js
tools.store.set('my-key', { foo: true })
tools.store.get('my-key')
```

This could operate inside of a `.txt` file, namespaced to the workflow's check run id or the sha or the workflow name (lots of options).

It's definitely possible that a library like this already exists - in which case, we should use it!

**Comment by ahmadnassri** [comment]
for such a tool, you'd want to consider writing to a buffer then writing to disk on process execution completion...

otherwise you might have write conflicts within async threads

**Comment by JasonEtco** [comment]
That's a great idea @ahmadnassri 👌 I'm not sure if Actions/Docker will honor a `process.on('exit')` handler, but its worth finding out.
