### ISSUE TITLE
Only allow certain events

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/actions-toolkit#36]
Events that trigger actions are defined in workflows, but there's nothing prevent me from using, for example, an action that is designed to inspect a `push` payload triggered by an `issues` event. So, it'd be nice to build a declarative way to fail an action run unless the event trigger matches what the action was expecting.

The real goal here is to avoid situations where a user is expecting an action to work for any event, but can't figure out why it won't with the event they're using.

Here's what I'm thinking:

```ts
interface ToolkitOpts {
  only?: string[]
}
class Toolkit {
  constructor (opts: ToolkitOpts) {
    const event = process.env.GITHUB_EVENT
    if (Array.isArray(opts) && !opts.includes(event)) {
      console.error(`Event ${event} is not supported by this action.`)
      process.exit(1)
    }
  }
}
```

**Comment by banyan** [comment]
@JasonEtco 

Thanks for this. it's useful! however, when I tried as following, 

```
const tools = new Toolkit({
  event: ['pull_request.opened', 'pull_request.synchronize'],
});
```

if I just edit pull request comment and triggered `pull_request.edited`, it would return exit 1. this looks something has failed even it just skipped. 

![image](https://user-images.githubusercontent.com/19625/52679824-a8bcbb00-2f79-11e9-9601-5249f922de72.png)

should we allow to return 78 in that case? https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/ what do you think?

**Comment by JasonEtco** [comment]
Oooh! This is great feedback. I'm guessing a `neutral` code would make more sense 🤔 @banyan would you be open to opening a pull request? Ideally, that'd use the `exit.neutral()` method added in #39.

**Comment by banyan** [comment]
@JasonEtco 

Thanks! I've just sent a PR: https://github.com/JasonEtco/actions-toolkit/pull/44
