### ISSUE TITLE
Provide a logger

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/actions-toolkit#5]
I'm not sure what the goals here are, but I find that when I'm debugging an action its difficult to visually parse the logs. I'd like to explore a better logging solution, one that `actions-toolkit` can help with.

Something like this, which shows the logger name and where in the code the logs come from:

```js
tools.log('Something happened!')
// => [action index.js:12:3] Something happened!
```

#### Some loggers

* [Bunyan](https://github.com/trentm/node-bunyan)
* [Winston](https://github.com/winstonjs/winston)
* [Pino](https://github.com/pinojs/pino)

**Comment by tcbyrd** [comment]
[Winston](https://github.com/winstonjs/winston) is the other one I've wanted to look at, and seems like it's the more popular tool than Bunyan in the last few months ([Buyan may also not be maintained](https://github.com/trentm/node-bunyan/issues/586)?)

**Comment by tcbyrd** [comment]
Oh that's interesting. And yeh both Winston and Bunyan are more aimed at production logging use cases. A reporter like that would definitely be a better fit for Actions.

**Comment by JasonEtco** [comment]
I've got a local branch implementing [Signale](https://github.com/klaussinani/signale), and with some light tweaking its super nice. The icons are easier to find in the logs, and it supports all the things we'd want like prefixes, different log types, etc etc. Probably gonna go with that!
