### ISSUE TITLE
A logo for this library

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/actions-toolkit#51]
I'd like this library to have a logo! Here's where it'd go in the README:

<img width="996" alt="image" src="https://user-images.githubusercontent.com/10660468/52966747-0c7a2600-3376-11e9-9e4d-38616c9fe66e.png">

## Motivation

I read somewhere (I can't find the post but would absolutely love to re-read) that talked about the power of branding for open source projects. Having an image in your mind is a lot more memorable than a name or a line of code. Plus, it adds some legitimacy to show that the project has gotten real attention.

## Inspiration

* The 🛠 emoji
* The play button logo for GitHub Actions:

![](https://avatars0.githubusercontent.com/u/44036562?s=128&v=4)

## How you can help

If you're interested in contributing this, that'd be _amazing_. You can drop some potential directions in this issue and we can talk about them!

**Comment by JohnPhamous** [comment]
I'll give this a go

**Comment by JohnPhamous** [comment]
![github-actions-toolkit-design-1](https://user-images.githubusercontent.com/16027268/52983406-e10c3100-339f-11e9-8442-ba42a7d7d048.jpg)
![github-actions-toolkit-design-2](https://user-images.githubusercontent.com/16027268/52983408-e23d5e00-339f-11e9-9155-69ac9dd65880.jpg)
![github-actions-toolkit-design-3](https://user-images.githubusercontent.com/16027268/52983731-5debda80-33a1-11e9-87b6-5e195bd7d2de.jpg)
![github-actions-toolkit-design-4](https://user-images.githubusercontent.com/16027268/52984014-701a4880-33a2-11e9-874e-50878a119360.jpg)

**Comment by JasonEtco** [comment]
Ooh awesome @JohnPhamous! These are really cool directions. I think I'm a fan of a circular shape - the third one feel closest. Not sure about the colors though; I find them a little too bright. I like that it looks like a bunch of assorted items in a little "toolbox."

Maybe something like this, reusing the gradient from the https://github.com/actions logo...

![image](https://user-images.githubusercontent.com/10660468/52985551-5ab51680-33c2-11e9-9d34-f03f65f1bae4.png)

Also playing around a bit with the bottom of the wrench (the little bolt negative space). I'd prefer something a lot less visually

![image](https://user-images.githubusercontent.com/10660468/52985285-2bea7080-33c1-11e9-882e-397a6526117e.png)

**Comment by JohnPhamous** [comment]
@JasonEtco Love the changes you made to the 3rd one. I'll take your feedback and make the changes sometime this weekend.

**Comment by bryanmacfarlane** [comment]
![actions-toolkit](https://user-images.githubusercontent.com/919564/56442589-5a9c9e80-62bf-11e9-9c10-af799efadda7.png)

**Comment by bryanmacfarlane** [comment]
In all the variations, I like the circle and somehow tying back into the actions logo.  The allen wrench hole with circle and tie back to action logo is nice.

**Comment by phatbhoy67** [comment]
A couple of options which give a nod to the wrench. 
![actions-toolkit](https://user-images.githubusercontent.com/18670428/69082142-69a32500-0a37-11ea-8122-0f474d51ee37.png)
