### ISSUE TITLE
Add a `secrets` option to the constructor

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/actions-toolkit#65]
Similar to the `events` option from #36, I'd like the Toolkit constructor to have a `secrets` option that does exactly the same kind of thing: will exit with a failure if the required secrets are not present. This should be a declarative, clear way of saying "this action won't work without these secrets."

```js
new Toolkit({
  secrets: ['GITHUB_TOKEN']
})
```

**Comment by gr2m** [comment]
I like, great IDEA!

I think you could somewhat enforce by defining getters which would only work if the secrets are defined as shown above

```js
toolkit.secrets.get('GITHUB_TOKEN')
```

I think you could also implement `toolkit.secrets.GITHUB_TOKEN` using [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)

**Comment by JasonEtco** [comment]
ooooooooo that's a great idea. I do want it to the secrets to be optional - so if I say:

```
new Toolkit({
  secrets: ['GITHUB_TOKEN']
})
```

I should still be allowed to access `process.env.SOME_OTHER_SECRET`.

**Comment by gr2m** [comment]
good point, secrets might be optional 🤔

In these cases you’d usually check if the ENV variable is set, you could provide a method like `toolkit.secrets.isProvided('GITHUB_TOKEN')`

Maybe it’s overkill 🤷‍♂️
