### ISSUE TITLE
Not all feather icons are supported by actions

### ISSUE THREAD

**Issue by rachmari** [JasonEtco/actions-toolkit#68]
The new questionnaire allows you to choose unsupported feather icons. If the documentation is correct, I don't think we support these icons:

chrome
codepen
coffee
figma
frown
github
gitlab
instagram
key
linkedin
meh
mouse-pointer
pen-tool
slack
smile
trello
twitter
x-octagon
youtube

The documentation over [here](https://developer.github.com/actions/creating-github-actions/creating-a-docker-container/#supported-feather-icons) lists the icons that are supported right now.

**Comment by JasonEtco** [comment]
That's true! We can filter those out [in the script that generates the `.json` file](https://github.com/JasonEtco/actions-toolkit/blob/master/scripts/update-feather-icons.js) pretty easily. However, I'm concerned with getting the list of icons that GitHub _does not_ support 🤔 We could go so far as to parse the doc site, but that's a little dicey.

cc @macklinu ✨

**Comment by gr2m** [comment]
> We could go so far as to parse the doc site, but that's a little dicey

Oh I gotcha, I did this so often now, happy to help. We could create a separate package that returns all supported GitHub Action icons and auto-updates. It would be similar to [octokit/webhooks](https://github.com/octokit/webhooks), just one document page that a script would call and turn into JSON, then create a PR if something changed during a nightly cron job

**Comment by macklinu** [comment]
> We could create a separate package that returns all supported GitHub Action icons and auto-updates. It would be similar to octokit/webhooks, just one document page that a script would call and turn into JSON, then create a PR if something changed during a nightly cron job

I like that approach. This is something that came up initially in #57 (see https://github.com/JasonEtco/actions-toolkit/pull/57#discussion_r261053724 for some history) but ended up choosing the official feather-icons icon names list vs. parsing the GitHub Actions site. However, I think running a nightly cron job to keep supported icon names up to date sounds good - let me know if I can help with that here or in another repo. 👍

**Comment by JasonEtco** [comment]
Thanks for the suggestions y'all ❤️ 

> running a nightly cron job to keep supported icon names up to date sounds good - let me know if I can help with that here or in another repo.

If we go down that route, definitely in favor of it being a separate repo (potentially as a GitHub Action 😱)

**Comment by gr2m** [comment]
+1 for separate repo, this might be useful to others, too. And besides publishing to npm, you could also publish the JSON to GitHub pages so non-npm tools could easily load a machine-readable format. I do that for octokit/routes: https://octokit.github.io/routes/

**Comment by alex-page** [comment]
I have updated the links in the hope that won't cause confusion.
