### ISSUE TITLE
minimist argument as string with space breaking

### ISSUE THREAD

**Issue by alex-page** [JasonEtco/actions-toolkit#81]
I have an argument `--test="hello world"`. 

Using `minimist` not through this library the output is 
```
{ _: [], test: 'hello world' }
```

Using this library it separates the string values into 
```
{ _: [ 'world\'' ],  test: '\'hello' }
```

I noticed you parse the arguments, but I think something seems a bit off.

**Comment by JasonEtco** [comment]
Are you running into this locally by running the file through `node <file>`, or through a `main.workflow` file on GitHub? If the latter, could you share the file contents?

**Comment by alex-page** [comment]
Through a `main.workflow`:

```
workflow "✨Add new issues to projects" {
  resolves = ["alex-page/add-new-issue-project"]
  on = "issues"
}

action "alex-page/add-new-issue-project" {
  uses = "alex-page/add-new-issue-project@master"
  args = "--projectnumber 1 --projectcolumn='To do'"
  secrets = ["GITHUB_TOKEN"]
}
```

**Comment by JasonEtco** [comment]
Thanks for that info @alex-page 🙏 That all _looks_ correct; I'll do some more digging when I get a chance. You might also have more success by doing:

```diff
-   args = "--projectnumber 1 --projectcolumn='To do'"
+   args = ["--projectnumber", 1, "--projectcolumn", "To do"]
```

**Comment by alex-page** [comment]
Oh ok nice! I'll do that as a temporary solution. Thank you 💯

**Comment by JasonEtco** [comment]
That's... odd. There's definitely something screwy going on.

**Comment by JasonEtco** [comment]
Running it locally, I get the expected output:

```js
// test.js
const { Toolkit } = require('actions-toolkit')
const tools = new Toolkit()
console.log(tools.arguments)
```

<img width="442" alt="image" src="https://user-images.githubusercontent.com/10660468/56060764-c1f1a600-5d35-11e9-96f8-20b790337eaf.png">

So its presumably something in the workflow parser.

**Comment by alex-page** [comment]
Yeah something is going on. I tried this: 
```
args = "[ 1, 'To do']"
```

and got this:
```
{ _: [ '[', '1,', '\'To', 'do\']' ] }
```

**Comment by JasonEtco** [comment]
That makes sense - you've got quotes around the array:

```diff
- args = "[ 1, 'To do']"
+ args = [ 1, "To do"]
```

I _think_ that single quotes vs. double quotes matters, or at least they're being syntax-highlighted differently.

**Comment by JasonEtco** [comment]
Doing `console.log(process.argv)` shows me:

```
[ '/usr/local/bin/node', '/index.js', '1', 'To do' ]
```

So that's looking good with a well-formatted `args` array!

**Comment by alex-page** [comment]
The number definitely confused me. Thanks for the help I definitely made a mistake with the string around the array. It seems to be happy now:
```
args = [ "1", "To do"]
```
```
{ _: [ 1, 'To do' ] }
```

**Comment by JasonEtco** [comment]
Ok great - now that I think about it, one-string args being parsed weirdly is actually a known bug. That's why [some actions have an entrypoint](https://github.com/actions/npm/blob/master/entrypoint.sh) like this:

```shell
#!/bin/sh
sh -c "npm $*"
```

So if its working as expected with an args array, I think the best we can do is clarify this behavior in the README 👌

**Comment by alex-page** [comment]
Ok that makes a lot more sense. A little information in the README would be great! Want me to make a Pull Request?

**Comment by JasonEtco** [comment]
That'd be wonderful, thanks ❤️
