### ISSUE TITLE
Specific events causes error logs

### ISSUE THREAD

**Issue by alex-page** [JasonEtco/actions-toolkit#84]
I understand this is the current approach for handling events but I think it should end without a failure.

> if present, the action will exit with a failing status code for any event that is not allowed.

This causes some confusion in the following scenario:
```js
{
  event: [ 'issues.opened' ],
}
```

In GitHub we cannot specify to run an action on `issues.opened` we can only run an action on `issues`. This means that all the actions that run on `issues` are going to get an error log. Which causes confusion like seen in this issue: https://github.com/alex-page/add-new-issue-project/issues/3

```
✖  error     Event `issues.assigned` is not supported by this action.
```

I think these actions should log with a neutral state if the user is using a specific action and they are using the parent event.

I can do a simple work around which is nice:
```js
if( tools.context.payload.action !== 'opened' ){
  tools.exit.neutral( `Event ${ action } is not supported by this action.` )
}
```

Let me know if you think this is an issue, happy to close it if there is some functionality I don't understand or reasoning for this approach.

**Comment by JasonEtco** [comment]
Thanks for opening this @alex-page 🙏 I see the issue here. This can be handled in user-land, but in a scenario where I want to act on `pull_request.opened`, it'd fail on any `pull_request.synchronize` - and post failure statuses to the same PR 👎  It'd be cool to do something like (pseudo-code):

```js
const [eventName, action] = eventString.split('.')

// Standard wrong event
if (eventName !== GITHUB_EVENT_NAME) {
  exit.failure()
}

// Right event, but wrong action
if (eventName === GITHUB_EVENT_NAME && action && action !== payload.action) {
  exit.neutral()
}
```

I'm super swamped at the moment - if you're interested in a PR that'd be 🔥 🙏

**Comment by alex-page** [comment]
I would love to help. I would like some clarity around this:

>  act on pull_request.opened, it'd fail on any pull_request.synchronize - and post failure statuses to the same PR 👎

The PR will get failing status checks when synchronise fires as it needs to exit the action with an error?

**Comment by JasonEtco** [comment]
I think that's the behavior right now - if I make an Action with this:

```js
new Toolkit({ event: 'pull_request.opened' })
```

```workflow
workflow "Stuff" {
  on = "pull_request"
}
```

It will exit with a failure whenever I push the the PR (kicking off a `pull_request.synchronize`). It should instead exit neutral, otherwise it'll report a failing status. Does that help clarify things?

**Comment by alex-page** [comment]
Yeah definitely, thanks @JasonEtco

**Comment by JasonEtco** [comment]
I'm going to close this issue since the behavior is different in Actions v2. Thanks for opening!
