### ISSUE TITLE
Creating a pull request review

### ISSUE THREAD

**Issue by dorongutman** [JasonEtco/actions-toolkit#85]
I want to have a slash command like `/emergency-approve` that will create an approved review by someone (either the author itself, if that's possible, or by a bot user).
While the usage isn't relevant, I know people have opinions on such a behaviour so I'll just say that this is to allow a designated person(s) to bypass the requirement of an approved review to merge a pull request to a protected branch, in case we must deploy an urgent fix.

I started by creating a filter of a issue comment directly in github actions, pointing to another filter of the hardcoded username of the designated user, and when I got to the actual action of creating the approval I tried messing around with https://github.com/actions/github, but it only have comments, labels, and assignments. 
So I forked it and tried duplicating and adjusting the comment logic, but I can't seem to understand how do I use the context to have the relevant needed information (repo, pull request) but also provide an `event` of type `APPROVE` and maybe an approve comment saying it was an emergency approval.

This is the code I got to (in the forked https://github.com/actions/github repo) but I guess I can do everything directly by creating a complete action using this repo.
```typescript
async function doApprove() {
  filterAction(tools.arguments.action)
  const body = tools.arguments._.slice(1).join(' ')
  tools.log.info('reason', body)
  return checkStatus(
    await tools.github.pulls.createReview(tools.context.issue({body})) // this is where I don't understand how to add the additional information, specifically the "event" of value "APPROVE"
  )
}
```

**Comment by JasonEtco** [comment]
Hey @dorongutman 👋 I'm not sure if you're asking a question here - I'm going to close this issue but feel free to reopen if I've missed something. Either way, seems like a cool idea ✨

**Comment by dorongutman** [comment]
@JasonEtco it indeed was a question about how to achieve this, as I wasn't able to do that.

**Comment by JasonEtco** [comment]
Ah I see - to create a review you'd want:

```js
await tools.github.pulls.createReview({
  ...tools.context.issue
  body,
  event: 'APPROVE'
})
```

**Comment by afwn90cj93201nixr2e1re** [comment]
@JasonEtco 

can you help little bit pls?

I have a workflow:

```yaml
name: 'Build from comment'
on:
    issue_comment:
        types: [created]

jobs:
    build-linux:
        if: contains(github.event.comment.body,'./build')
        name: Linux
        runs-on: ubuntu-latest
```

So, it's trigger every time when comment created.
It works well. Btw i don't wanna call it each time when comment was created, i need only call it when comment created and contain 'build' (blue called when 'blue' is not exists
![изображение](https://user-images.githubusercontent.com/9306996/79052365-8d087f80-7c25-11ea-9d04-f21a65e71013.png)
)
, else ignore, so, i found this:

![изображение](https://user-images.githubusercontent.com/9306996/79052349-65191c00-7c25-11ea-87b6-ac5c1a90b516.png)


btw there's no examples.

Can you help with that?

**Comment by JasonEtco** [comment]
@afwn90cj93201nixr2e1re do you mind opening a new issue for your question? It seems unrelated to this one.

**Comment by afwn90cj93201nixr2e1re** [comment]
So fast.
Yep, i know. I don't wanna, if you can, just describe it on ur blog, and i gonna read. If u can't, so... then, thanks for fast response.

**Comment by JasonEtco** [comment]
I understand that you don’t wanna, but a new issue with your question in it is how I’ll be able to help you.

**Comment by afwn90cj93201nixr2e1re** [comment]
np, thx.

**Comment by afwn90cj93201nixr2e1re** [comment]
so, i ended up with https://github.com/marketplace/run-actions-from-comment
