### ISSUE TITLE
Note about Architectural Context & Added Value

### ISSUE THREAD

**Issue by evdama** [JasonEtco/actions-toolkit#86]
Since Github Actions is an entirely new concept it's hard for people to grasp how _actions-toolkit_ fits in this context of github actions. Is it a way to write actions inside Docker Containers using node.js? Is it an extension to the textual way of writing actions on github? Is it something optional entirely, and where is it executed after all?

People don't know yet what to make of github actions, let alone some utility library (is it one?) like actions-toolkit. It would be great if there were a few sentences at the beginning telling a new user why he would want to look into actions-toolkit and what the added value of using it might be.

**Comment by JasonEtco** [comment]
Hey @evdama - thanks for bringing this up. I think that this line from the README:

>  A toolkit for building GitHub Actions in Node.js

...says enough. I'd be up for linking to some additional resources at the end of the README though, like [awesome-actions](https://github.com/sdras/awesome-actions) or [my blog post on building Actions with Node.js](https://jasonet.co/posts/building-github-actions-in-node).

If you'd like to open a PR for ☝️ that'd be great!

**Comment by evdama** [comment]
said and done https://github.com/JasonEtco/actions-toolkit/pull/87

I kept to the information you gave in your initial blog post :)
