### ISSUE TITLE
@octokit/graphql types

### ISSUE THREAD

**Issue by kevinpollet** [JasonEtco/actions-toolkit#91]
As mentioned in #88, I've a first implementation of `@octokit/graphql` types which can be contributed to `DefinitelyTyped` when I've added the tests and checked that everything is working. You can see my work here: https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...kevinpollet:add-octokit-graphql-types.

WDYT?

**Comment by gr2m** [comment]
we are working on rewriting the `@octokit/*` libraries to typescript right now. We just finished https://github.com/octokit/endpoint.js and https://github.com/octokit/request.js. https://github.com/octokit/app.js is work in progress and https://github.com/octokit/graphql would be next. If you like you can help us out with it :) I’ve described our build setup at https://gist.github.com/gr2m/5dd2ec6e3a04c3dc79f0cbb46decbe46

**Comment by kevinpollet** [comment]
Awesome 👍

I think someone is already on it, I've seen that there is a recently updated branch named `typescript` in the`graphql` repository (https://github.com/octokit/graphql.js/tree/typescript). 

Let me know if I can do something or when it's done, if you want I will integrate it in this project.

**Comment by JasonEtco** [comment]
👋 Closed by #106
