### ISSUE TITLE
Logging Issue

### ISSUE THREAD

**Issue by coreybutler** [JasonEtco/actions-toolkit#98]
Given the following code:

```javascript
tools.log.info({
  owner: process.env.GITHUB_ACTOR,
  repo: process.env.GITHUB_REPOSITORY.split('/').pop(),
  tag: tagName,
  message: process.env.hasOwnProperty('TAG_MESSAGE')
    ? process.env.TAG_MESSAGE
    : `Version ${pkg.version}`,
  sha: process.env.GITHUB_SHA,
  type: 'commit'
})
```

**Actual Output**: `Version 1.0.0`

**Expected Output**: (object)

```json
{
  "owner": "...",
  "repo": "....",
  "tag": "1.0.0",
  "message": "Version 1.0.0",
  "sha": "...",
  "type": "commit"
}
```

---

It appears as though `message` is being picked up by the logger instead of dumping out the object. It works with other objects. It only fails when `message` is an attribute of the object.

**Comment by JasonEtco** [comment]
Thanks for the report here @coreybutler, sorry for the (very long) delay 🙏 I think this is a "feature" of [Signale](https://github.com/klaussinani/signale), the logger in use. I agree that it's confusing, but that's the behavior they decided on. I think that encountering it by mistake is a fairly uncommon edge-case; I'm going to close this issue, but if it comes up again we can take a look at using a different logger 👍
